Use absolute paths for ssh_config
blueboxgroup/ursula-cli pull request #55
Opened 2016-10-01 00:42 UTC by j2sol

Use of a relative path is fragile, and recently broke with Ansible
2.1.2.0 ( https://github.com/ansible/ansible/issues/17770 ). By using
the full path we avoid this problem and any future ones.

2016-10-02 05:17 UTC, masteinhauser requested changes

2016-10-02 05:17 UTC, masteinhauser commented on ursula_cli/shell.py
>      if os.path.isfile(ansible_ssh_config_file):
This seems like a bug and that you meant to use `ansible_ssh_config_file`?

2016-10-02 21:14 UTC, j2sol commented on ursula_cli/shell.py
>      if os.path.isfile(ansible_ssh_config_file):
Fixed!

2016-10-05 19:57 UTC, masteinhauser approved these changes

2016-10-10 13:44 UTC, j2sol commented
@masteinhauser Did you get a chance to test this? I'd like to get this merged.

2016-10-10 16:09 UTC, merged